name: CI/CD Pipelinezz

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install Flask Flask-PyMongo

      - name: Run Python tests
        run: |
          . venv/bin/activate
          # ここでテストスクリプトを実行 (例: pytest)
          # pytest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js dependencies
        run: |
          cd client
          npm install

      - name: Build React app
        run: |
          cd client
          npm run build

      - name: Deploy to server
        # ここでデプロイステップを記述